services:
  postgres:
    image: postgres:17
    env_file:
      - .env

  redis:
    image: redis:7

  backend:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    command: [ "/backend/docker/server.sh" ]
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
    command: [ "/backend/docker/celery.sh" ]
    depends_on:
      - redis
      - backend
    ports:
      - "5555:5555"