[tool.mypy]
plugins = ["pydantic.mypy"]
files = ['.']
ignore_missing_imports = true
exclude = [
    'env.*',
    'venv.*',
    'migrations.*'
]
follow_imports_for_stubs = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
show_error_context = true
show_column_numbers = true
pretty = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.yapf]
ALIGN_CLOSING_BRACKET_WITH_VISUAL_INDENT = true
ALLOW_MULTILINE_LAMBDAS = false
ALLOW_MULTILINE_DICTIONARY_KEYS = true
ALLOW_SPLIT_BEFORE_DEFAULT_OR_NAMED_ASSIGNS = true
ALLOW_SPLIT_BEFORE_DICT_VALUE = true
ARITHMETIC_PRECEDENCE_INDICATION = false
BLANK_LINE_BEFORE_CLASS_DOCSTRING = false
BLANK_LINE_BEFORE_MODULE_DOCSTRING = false
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = false
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION = 2
BLANK_LINES_BETWEEN_TOP_LEVEL_IMPORTS_AND_VARIABLES = 2
COALESCE_BRACKETS = true
COLUMN_LIMIT = 79
CONTINUATION_ALIGN_STYLE = "FIXED"
CONTINUATION_INDENT_WIDTH = 4
DEDENT_CLOSING_BRACKETS = true
DISABLE_ENDING_COMMA_HEURISTIC = false
EACH_DICT_ENTRY_ON_SEPARATE_LINE = true
FORCE_MULTILINE_DICT = false
INDENT_BLANK_LINES = false
INDENT_CLOSING_BRACKETS = false
INDENT_DICTIONARY_VALUE = false
INDENT_WIDTH = 4
JOIN_MULTIPLE_LINES = true
NO_SPACES_AROUND_SELECTED_BINARY_OPERATORS = '&,|,^,/,*,@,**'
SPACE_BETWEEN_ENDING_COMMA_AND_CLOSING_BRACKET = true
SPACE_INSIDE_BRACKETS = false
SPACES_AROUND_DEFAULT_OR_NAMED_ASSIGN = false
SPACES_AROUND_DICT_DELIMITERS = false
SPACES_AROUND_LIST_DELIMITERS = false
SPACES_AROUND_POWER_OPERATOR = true
SPACES_AROUND_SUBSCRIPT_COLON = false
SPACES_AROUND_TUPLE_DELIMITERS = false
SPACES_BEFORE_COMMENT = 2
SPLIT_ALL_COMMA_SEPARATED_VALUES = false
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES = false
SPLIT_ARGUMENTS_WHEN_COMMA_TERMINATED = false
SPLIT_BEFORE_ARITHMETIC_OPERATOR = true
SPLIT_BEFORE_BITWISE_OPERATOR = false
SPLIT_BEFORE_CLOSING_BRACKET = true
SPLIT_BEFORE_DICT_SET_GENERATOR = true
SPLIT_BEFORE_DOT = true
SPLIT_BEFORE_EXPRESSION_AFTER_OPENING_PAREN = true
SPLIT_BEFORE_FIRST_ARGUMENT = true
SPLIT_BEFORE_LOGICAL_OPERATOR = false
SPLIT_BEFORE_NAMED_ASSIGNS = true
SPLIT_COMPLEX_COMPREHENSION = true
USE_TABS = false


[tool.yapfignore]
ignore_patterns = [
    'venv/**/*',
]

[tool.isort]
extend_skip = ["env.py"]
extend_skip_glob = ["migrations", "test/*"]
skip_gitignore = true
multi_line_output = 5
use_parentheses = true
atomic = true
lines_after_imports = 2
combine_as_imports = true
combine_star = true
include_trailing_comma = true
force_alphabetical_sort_within_sections = true
force_sort_within_sections = true
ensure_newline_before_comments = true
honor_noqa = true
remove_redundant_aliases = true
float_to_top = true
color_output = true
dedup_headings = true
combine_straight_imports = true
star_first = true
