"""check for changes

Revision ID: 456706f5f582
Revises: c50c06f11673
Create Date: 2024-11-07 15:44:54.620169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '456706f5f582'
down_revision: Union[str, None] = 'c50c06f11673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_refresh_tokens',
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_issued_refresh_tokens_device_id'), 'issued_refresh_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_issued_refresh_tokens_sub'), 'issued_refresh_tokens', ['sub'], unique=False)
    op.drop_index('ix_issued_tokens_device_id', table_name='issued_tokens')
    op.drop_index('ix_issued_tokens_sub', table_name='issued_tokens')
    op.drop_table('issued_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_tokens',
    sa.Column('sub', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sub', 'device_id', name='issued_tokens_pkey')
    )
    op.create_index('ix_issued_tokens_sub', 'issued_tokens', ['sub'], unique=False)
    op.create_index('ix_issued_tokens_device_id', 'issued_tokens', ['device_id'], unique=False)
    op.drop_index(op.f('ix_issued_refresh_tokens_sub'), table_name='issued_refresh_tokens')
    op.drop_index(op.f('ix_issued_refresh_tokens_device_id'), table_name='issued_refresh_tokens')
    op.drop_table('issued_refresh_tokens')
    # ### end Alembic commands ###
