"""Edit Users

Revision ID: 4f07926a8ace
Revises: 50897b8483e6
Create Date: 2024-08-29 19:52:24.280618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4f07926a8ace'
down_revision: Union[str, None] = '50897b8483e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
        'refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False
        )
    )
    op.add_column(
        'users',
        sa.Column(
        'nickname', sa.VARCHAR(), autoincrement=False, nullable=False
        )
    )
    # ### end Alembic commands ###
