"""Add the Users table

Revision ID: 50897b8483e6
Revises: 
Create Date: 2024-08-25 19:27:43.716585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '50897b8483e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
        'nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
        'hashed_password',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=False
        ),
        sa.Column(
        'refresh_token',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=False
        ), sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
