"""use ulid as a user id

Revision ID: 59510dd95873
Revises: a4f5331f9f26
Create Date: 2024-11-07 14:20:53.307331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '59510dd95873'
down_revision: Union[str, None] = 'a4f5331f9f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'issued_tokens',
        'sub',
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False
    )
    op.alter_column(
        'users',
        'id',
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=26),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'id',
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=26),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'issued_tokens',
        'sub',
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
