"""Add the table with issued tokens

Revision ID: a7dde7087294
Revises: e37264d243fd
Create Date: 2024-11-06 23:05:53.123845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a7dde7087294'
down_revision: Union[str, None] = 'e37264d243fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'issuedtokens', sa.Column('sub', sa.Integer(), nullable=False),
        sa.Column(
        'device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ), sa.Column('exp', sa.Integer(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('sub', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issuedtokens')
    # ### end Alembic commands ###
