"""use ulid as a jti

Revision ID: c50c06f11673
Revises: 59510dd95873
Create Date: 2024-11-07 14:53:59.600426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c50c06f11673'
down_revision: Union[str, None] = '59510dd95873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'issued_tokens',
        sa.Column(
        'jti', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        )
    )
    op.create_index(
        op.f('ix_issued_tokens_device_id'),
        'issued_tokens', ['device_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_issued_tokens_sub'), 'issued_tokens', ['sub'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_tokens_sub'), table_name='issued_tokens')
    op.drop_index(
        op.f('ix_issued_tokens_device_id'), table_name='issued_tokens'
    )
    op.drop_column('issued_tokens', 'jti')
    # ### end Alembic commands ###
